version: '3.8'

services:

  oracle-db:
    image: gvenzl/oracle-free:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: 123456
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5

#  app:
#    build: .
#    container_name: spring-app
#    ports:
#      - "8080:8080"
#    depends_on:
#      oracle-db:
#        condition: service_healthy
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
#      SPRING_DATASOURCE_USERNAME: SYSTEM
#      SPRING_DATASOURCE_PASSWORD: 123456
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  oracle-data:
